// Code generated by qtc from "Workspace.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/Workspace.html:1
package views

//line views/Workspace.html:1
import (
	"github.com/kyleu/npn/app"
	"github.com/kyleu/npn/app/controller/cutil"
	"github.com/kyleu/npn/app/util"
	"github.com/kyleu/npn/views/components"
	"github.com/kyleu/npn/views/layout"
)

//line views/Workspace.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/Workspace.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/Workspace.html:9
type Workspace struct{ layout.Basic }

//line views/Workspace.html:11
func (p *Workspace) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/Workspace.html:11
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/Workspace.html:13
	components.StreamSVGRefIcon(qw422016, `app`, ps)
//line views/Workspace.html:13
	qw422016.E().S(util.AppName)
//line views/Workspace.html:13
	qw422016.N().S(`</h3>
    <em>v`)
//line views/Workspace.html:14
	qw422016.E().S(as.BuildInfo.Version)
//line views/Workspace.html:14
	qw422016.N().S(`, started `)
//line views/Workspace.html:14
	qw422016.E().S(util.TimeRelative(&as.Started))
//line views/Workspace.html:14
	qw422016.N().S(`</em>
  </div>
  <link href="/assets/vendor/`)
//line views/Workspace.html:16
	qw422016.E().S(util.AppKey)
//line views/Workspace.html:16
	qw422016.N().S(`.css" rel="stylesheet">
  <script src="/assets/vendor/vendor.js"></script>
  <script src="/assets/vendor/`)
//line views/Workspace.html:18
	qw422016.E().S(util.AppKey)
//line views/Workspace.html:18
	qw422016.N().S(`.js"></script>
  <script src="/assets/vendor/editor/editor.js" defer="defer"></script>
  <script>init(true, true);</script>
`)
//line views/Workspace.html:21
}

//line views/Workspace.html:21
func (p *Workspace) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/Workspace.html:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Workspace.html:21
	p.StreamBody(qw422016, as, ps)
//line views/Workspace.html:21
	qt422016.ReleaseWriter(qw422016)
//line views/Workspace.html:21
}

//line views/Workspace.html:21
func (p *Workspace) Body(as *app.State, ps *cutil.PageState) string {
//line views/Workspace.html:21
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Workspace.html:21
	p.WriteBody(qb422016, as, ps)
//line views/Workspace.html:21
	qs422016 := string(qb422016.B)
//line views/Workspace.html:21
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Workspace.html:21
	return qs422016
//line views/Workspace.html:21
}
